version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: 'test_db'
      POSTGRES_PASSWORD: 'test'
      POSTGRES_USER: 'test'
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - test:/var/lib/postgres
volumes:
  test:
